name: helpdesk
description: Ticketing Interface.

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-255.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  http: ^0.13.5

  # Firebase
  firebase_core: ^2.4.0
  firebase_auth: 4.2.1
  google_sign_in: ^5.4.2
  cloud_firestore: ^4.2.0

  # Annotations
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  # Bloc
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0
  hydrated_bloc: ^9.0.0

  # Doc Decoding
  yaml: ^3.1.1
  flutter_markdown: ^0.6.13

  # UI
  scroll_to_index: 3.0.1
  clipboard: ^0.1.3
  animations: ^2.0.7

  # System
  logger: ^1.1.0
  connectivity_plus: ^3.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  package_info_plus: 3.0.1
  url_launcher: ^6.1.6
  go_router: ^5.1.5

  # Utils
  faker: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  json_serializable: ^6.5.4
  freezed: ^2.2.1
  dependency_validator: ^3.2.2
  
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  fonts:

    - family: RobotoMono
      fonts:
      - asset: assets/fonts/RobotoMono-Regular.ttf
        weight: 400

    - family: NotoSans
      fonts:
      - asset: assets/fonts/NotoSans-Thin.ttf
        weight: 100
      - asset: assets/fonts/NotoSans-ThinItalic.ttf
        weight: 100
        style: italic
      - asset: assets/fonts/NotoSans-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/NotoSans-ExtraLightItalic.ttf
        weight: 200
        style: italic
      - asset: assets/fonts/NotoSans-Light.ttf
        weight: 300
      - asset: assets/fonts/NotoSans-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/NotoSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/NotoSans-Italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/NotoSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/NotoSans-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/NotoSans-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/NotoSans-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/NotoSans-Bold.ttf
        weight: 700
      - asset: assets/fonts/NotoSans-BoldItalic.ttf
        weight: 700
        style: italic
