// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaq3IsXPNhFZ4m4ybJuI3T_I24HSY38Cw',
    appId: '1:824508506748:web:c253e12ca115c5246f9ff9',
    messagingSenderId: '824508506748',
    projectId: 'flatsy-help-desk',
    authDomain: 'flatsy-help-desk.firebaseapp.com',
    storageBucket: 'flatsy-help-desk.appspot.com',
    measurementId: 'G-YTEVVLCK9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUtdi_rwfz8bYeg7HRkPl2KrRmFxupSkE',
    appId: '1:824508506748:android:87a6c50ea2f638206f9ff9',
    messagingSenderId: '824508506748',
    projectId: 'flatsy-help-desk',
    storageBucket: 'flatsy-help-desk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJmziYpQ1hRPIZEuc3bKI8yfoPPKwh4mg',
    appId: '1:824508506748:ios:a741ff3ef2ac8ccb6f9ff9',
    messagingSenderId: '824508506748',
    projectId: 'flatsy-help-desk',
    storageBucket: 'flatsy-help-desk.appspot.com',
    iosClientId: '824508506748-eh555duqi4sp88gvc5vc5s8ep8tf2db3.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpdesk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJmziYpQ1hRPIZEuc3bKI8yfoPPKwh4mg',
    appId: '1:824508506748:ios:a741ff3ef2ac8ccb6f9ff9',
    messagingSenderId: '824508506748',
    projectId: 'flatsy-help-desk',
    storageBucket: 'flatsy-help-desk.appspot.com',
    iosClientId: '824508506748-eh555duqi4sp88gvc5vc5s8ep8tf2db3.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpdesk',
  );
}
